### ISSUE TITLE
Error with legend on firefox

### ISSUE THREAD

**Issue by targos** [NPellet/jsGraph#53]
https://github.com/NPellet/jsGraph/blob/master/src/graph.legend.js#L195
https://bugzilla.mozilla.org/show_bug.cgi?id=612118

I'll provide a testcase when I have time

**Comment by NPellet** [comment]
Yeah ok but technically the element should be in the DOM when the method is
called...

2015-09-01 13:56 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
you mean the spectra_displayer should create the legend at another point in time, or you expect it to work as is ?

**Comment by NPellet** [comment]
Well... my code is correct (it seems)

The update method is only called after the graph is in the main dom wrapper.
Now if the wrapper is not in the document, there's not much I can do. Maybe
add an observable...

So I would think the issue comes from the visualizer. But I don't have
Firefox here so I can't say for sure.

2015-09-01 14:18 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
I just checked, the graph is already in the dom when the method is called

**Comment by NPellet** [comment]
Ah oups. Then I need to install Firefox =)

**Comment by targos** [comment]
you can use the following testcase : http://direct.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/jcampViewer/view.json&dataURL=../testcase/data/jcampViewer/data.json

**Comment by NPellet** [comment]
Ok the problem is not the DOM, it's the display="none" attribute. I am committing an attempt to fix, can you let me know ?

v1.13.3-6

**Comment by targos** [comment]
it is fixed indeed. Thanks much!
